name: murshed_admin_panel
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  cached_network_image: ^3.3.0
  loader_overlay: ^2.2.0
  flutter_svg: ^2.0.8
  flutter_screenutil: ^5.7.0
  animate_do: ^3.1.2
  dropdown_button2: ^2.3.9
  elegant_notification: ^1.11.2
  flutter_animate: ^4.5.0
  animated_text_kit: ^4.2.2
  chat_bubbles: ^1.6.0
  responsive_framework: ^1.4.0
  gap: ^3.0.1
  recase: ^4.1.0
  # State Management
  flutter_riverpod: any
  riverpod: ^2.2.0

  #utils
  flutter_native_splash: ^2.3.4
  flutter_launcher_icons: ^0.13.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  url_launcher: ^6.2.3
  qr_flutter: ^4.1.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  url_strategy: ^0.2.0

  #routing
  go_router: ^8.0.1

  #localization
  easy_localization: ^3.0.0

  # depend reference
  intl: ^0.18.0
  easy_logger: ^0.0.2

  # Debugging and Testing
  logging: ^1.1.1

  # firebase
  firebase_storage: ^11.4.0
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.11.1
  firebase_core: ^2.20.0
  #local notifications
  flutter_local_notifications: ^15.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  change_app_package_name: ^1.1.0
  go_router_builder:
dependency_overrides:
  intl: ^0.19.0


flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/svgs/
    - assets/translations/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Black.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  web: true
